<?php
/**
 * Created by dai.yamaguchi
 * DATE: 2019/11/27
 *
 */

namespace EditTable;

use Encore\Admin\Widgets\Table;

class EditTable extends Table {

    /**
     * EditTable constructor.
     * @param $headers
     * @param $columns
     * @param $model
     */
    function __construct($headers, $columns, $model) {
        $rows = $model->get()->map(function ($row) use ($columns) {
            return $row->only($columns);
        })->toArray();
        parent::__construct($headers, $rows, []);
    }

    /**
     * @return string
     */
    function render() {
        return parent::render(); // TODO: Change the autogenerated stub
    }

}